name: bring2me
description: A new Flutter project.


version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  #autentication
  toast:
  meta:
  firebase_core: ^0.3.1+1
  firebase_auth: ^0.8.0
  #Botones-Social-netword
  flutter_auth_buttons: ^0.3.1
  #flutter_facebook_login: ^1.1.1
  #firebase datos
  firebase_database: ^2.0.2
  cupertino_icons: ^0.1.2
  #firebase imagenes
  firebase_storage: ^2.1.0+1
  image_picker: ^0.5.0+9
  firebase_analytics: ^2.0.3
  cloud_firestore: ^0.9.0
  rxdart: ^0.21.0
  location: ^2.3.3
  cloud_functions: ^0.1.2+1
  circle_wheel_scroll: ^0.0.1+1
  dropdown_menu: ^1.1.1
  google_maps_flutter: ^0.5.7
  google_maps_webservice: ^0.0.13
  flutter_screenutil: ^0.5.2
  geolocator: ^4.0.1
  flutter_google_places:  

dev_dependencies:
  flutter_test:
    sdk: flutter
  google_sign_in: ^4.0.1+1


flutter:


  uses-material-design: true

  assets:
      - assets/images/correo.png
      - assets/images/naveespacial.gif
      - assets/images/logo.png
      - assets/images/galeria.png
      - assets/images/alcohol.png
      - assets/images/all.png
      - assets/images/comida.png
      - assets/images/encomiendas.png
      - assets/images/farmacia.png
      - assets/images/regalo.png
      - assets/images/snacks.png
      - assets/images/supermercado.png
      - assets/images/image_01.png
      - assets/images/image_02.png
      - assets/images/logo1.png     

  fonts:
    - family: CustomIcons
      fonts:
        - asset: assets/CustomIcons.ttf

    - family: Poppins-Bold
      fonts:
        - asset: assets/Poppins-Bold.ttf

    - family: Poppins-Medium
      fonts:
        - asset: assets/Poppins-Medium.ttf  