name: bring2me
description: A new Flutter project.


version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  #autentication
  toast:
  meta:
  firebase_core: 
  firebase_auth: 
  #Botones-Social-netword
  flutter_auth_buttons: 
  #flutter_facebook_login: ^1.1.1
  #firebase datos
  firebase_database: 
  cupertino_icons: 
  #firebase imagenes
  firebase_storage: 
  image_picker: 
  firebase_analytics: 
  cloud_firestore: 
  rxdart: 
  location: 
  cloud_functions: 
  circle_wheel_scroll: 
  dropdown_menu: 
  google_maps_flutter: 
  google_maps_webservice:
  flutter_screenutil: 
  geolocator: 
  flutter_google_places:  
  firebase_dynamic_links: 
  intl: 
  #onesignal: ^1.1.0
  #firebase_messaging: ^5.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  google_sign_in: 


flutter:


  uses-material-design: true

  assets:
      - assets/images/correo.png
      - assets/images/naveespacial.gif
      - assets/images/logo.png
      - assets/images/galeria.png
      - assets/images/alcohol.png
      - assets/images/all.png
      - assets/images/comida.png
      - assets/images/encomiendas.png
      - assets/images/farmacia.png
      - assets/images/regalo.png
      - assets/images/snacks.png
      - assets/images/supermercado.png
      - assets/images/image_01.png
      - assets/images/image_02.png
      - assets/images/logo1.png     

  fonts:
    - family: CustomIcons
      fonts:
        - asset: assets/CustomIcons.ttf

    - family: Poppins-Bold
      fonts:
        - asset: assets/Poppins-Bold.ttf

    - family: Poppins-Medium
      fonts:
        - asset: assets/Poppins-Medium.ttf  