name: order_restaurant
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  #autentication
  cupertino_icons: 
  cloud_functions: ^0.4.1+1
  firebase_storage: 
  cloud_firestore: 
  image_picker: 
  toast:
  


 

dev_dependencies:
  flutter_test:
    sdk: flutter  


flutter:


  uses-material-design: true

  assets:
      - assets/images/galeria.png

  
